sudo: required

# not required, but less confusing if defined
language: C

services:
  - docker

env:
  - DISTRO=fedora:27 COMPILER=gcc
  - DISTRO=fedora:27 COMPILER=clang
  - DISTRO=debian:sid COMPILER=clang

script:
  - >
    docker run
    -v `pwd`:/tmp/build
    -w /tmp/build
    -e COMPILER=$COMPILER
    $DISTRO /bin/bash -ex .travis.sh
